(()=>{
const RELAY='https://tally-relay-anish.onrender.com';
const K={url:'tallysync_connector_url',code:'tallysync_office_code',company:'tallysync_selected_company'};
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const saved=()=>localStorage.getItem(K.url)||'http://127.0.0.1:9101';
const code=()=>localStorage.getItem(K.code)||'';
const selected=()=>{try{return JSON.parse(localStorage.getItem(K.company)||'null')}catch{return null}};
const txt=e=>(e?.innerText||e?.textContent||e?.value||'').replace(/\s+/g,' ').trim();
async function post(xml){const c=code();const u=c?`${RELAY}/api/device/${encodeURIComponent(c)}/xml`:saved().replace(/\/$/,'')+'/tally/xml';let r;try{r=await fetch(u,{method:'POST',headers:{'Content-Type':'text/xml;charset=utf-8'},body:xml,signal:AbortSignal.timeout(40000)})}catch(e){throw Error('Office connector/relay timeout. Connector online hai?')}const t=await r.text();if(!r.ok)throw Error(t.slice(0,300)||`HTTP ${r.status}`);return t}
async function collection(name,type,fetches,useCompany=true){const tag=useCompany&&selected()?.Name?`<SVCURRENTCOMPANY>${esc(selected().Name)}</SVCURRENTCOMPANY>`:'';return post(`<ENVELOPE><HEADER><VERSION>1</VERSION><TALLYREQUEST>Export</TALLYREQUEST><TYPE>Collection</TYPE><ID>${name}</ID></HEADER><BODY><DESC><STATICVARIABLES><SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>${tag}</STATICVARIABLES><TDL><TDLMESSAGE><COLLECTION NAME="${name}"><TYPE>${type}</TYPE><FETCH>${fetches}</FETCH></COLLECTION></TDLMESSAGE></TDL></DESC></BODY></ENVELOPE>`) }
function parse(raw,tags){const d=new DOMParser().parseFromString(raw,'text/xml');if(d.querySelector('parsererror'))throw Error('Invalid XML response');return [...d.querySelectorAll('LEDGER,STOCKITEM,VOUCHER,COMPANY')].map(n=>{const o={};tags.forEach(t=>{const q=n.querySelector(t)||n.querySelector(t.toUpperCase());o[t]=(q?.textContent||n.getAttribute(t)||n.getAttribute(t.toUpperCase())||'').trim()});return o}).filter(o=>Object.values(o).some(Boolean))}
function brand(){if(document.getElementById('anish-fixed-brand'))return;const b=document.createElement('div');b.id='anish-fixed-brand';b.textContent='ANISH TECHNOLOGIES';b.style.cssText='position:fixed;top:0;left:0;right:0;z-index:99998;height:46px;display:flex;align-items:center;justify-content:center;box-sizing:border-box;background:linear-gradient(135deg,#0b1220,#172554);color:#fff;font:800 18px/46px Arial,sans-serif;letter-spacing:2px;border-bottom:2px solid #2563eb;box-shadow:0 4px 18px #0003;pointer-events:none;white-space:nowrap';document.body.appendChild(b);document.body.style.paddingTop='46px'}
function hideOnlyOldButton(){document.querySelectorAll('button,a,[role="button"],input').forEach(el=>{if(el.closest('#ts-connect')||el.id==='anish-fixed-brand')return;const t=txt(el).toLowerCase();if(/^(🔗\s*)?(connect tally|tally connect|connect to tally)$/.test(t))el.style.setProperty('display','none','important')})}
async function loadCompanies(){const raw=await collection('Company Collection','Company','Name,Guid,MailingName,StateName,PinCode,PhoneNumber,Email,GSTIN',false);const rows=parse(raw,['Name','Guid','MailingName','StateName','PinCode','PhoneNumber','Email','GSTIN']);if(!rows.length)throw Error('TallyPrime me company open nahi hai ya company return nahi hui.');const old=selected();const chosen=rows.find(x=>old&&x.Name===old.Name)||rows[0];localStorage.setItem(K.company,JSON.stringify(chosen));window.dispatchEvent(new CustomEvent('tallysync:companies',{detail:{companies:rows,selected:chosen}}));return loadLiveData()}
async function loadLiveData(){if(!selected())throw Error('Company select nahi hui');const [l,s,v]=await Promise.all([collection('Live Ledgers','Ledger','Name,Parent,ClosingBalance,OpeningBalance,PhoneNumber,Email,GSTIN,Address'),collection('Live Stock','StockItem','Name,Parent,ClosingBalance,ClosingValue,BaseUnits,Rate'),collection('Live Vouchers','Voucher','Date,VoucherNumber,VoucherTypeName,PartyLedgerName,Amount,Reference,Narration')]);const ledgers=parse(l,['Name','Parent','ClosingBalance','OpeningBalance','PhoneNumber','Email','GSTIN','Address']);const stock=parse(s,['Name','Parent','ClosingBalance','ClosingValue','BaseUnits','Rate']);const all=parse(v,['Date','VoucherNumber','VoucherTypeName','PartyLedgerName','Amount','Reference','Narration']);const data={ledgers,stock,sales:all.filter(x=>/sales/i.test(x.VoucherTypeName||'')),purchase:all.filter(x=>/purchase/i.test(x.VoucherTypeName||''))};window.__tallyLiveData=data;window.dispatchEvent(new CustomEvent('tallysync:data',{detail:{company:selected(),data}}));return data}
function panel(){if(document.getElementById('ts-connect'))return;brand();const root=document.createElement('div');root.id='ts-connect';root.style.cssText='position:fixed;right:24px;bottom:24px;z-index:99999;font-family:Inter,Arial,sans-serif';root.innerHTML='<button id="ts-connect-btn" style="display:block;min-width:190px;padding:13px 20px;border:0;border-radius:12px;background:#0f172a;color:#fff;font-weight:800;cursor:pointer;box-shadow:0 8px 25px #0003">🔗 Connect Tally</button><div id="ts-modal" style="display:none;position:fixed;inset:0;background:#0f172a99;align-items:center;justify-content:center"><div style="background:#fff;width:min(560px,92vw);border-radius:18px;overflow:hidden"><div style="padding:20px;background:linear-gradient(135deg,#0f172a,#1e3a8a);color:#fff"><b style="font-size:21px">Connect TallyPrime</b><div style="font-size:12px;opacity:.8">Office computer connector + secure relay</div></div><div style="padding:20px"><label>Remote Office Code</label><input id="ts-code" value="'+esc(code())+'" placeholder="ANISH-XXXXXXXX" style="width:100%;box-sizing:border-box;margin:7px 0 14px;padding:12px;border:1px solid #cbd5e1;border-radius:10px"><details><summary>Advanced: direct connector URL</summary><input id="ts-url" value="'+esc(saved())+'" style="width:100%;box-sizing:border-box;margin-top:8px;padding:10px;border:1px solid #cbd5e1;border-radius:9px"></details><div style="display:flex;gap:8px;justify-content:flex-end;margin-top:16px"><button id="ts-close">Cancel</button><button id="ts-test" style="background:#0f172a;color:#fff">Test Tally</button></div><div id="ts-status" style="margin-top:14px;font-size:13px"></div></div></div></div>';
document.body.appendChild(root);const modal=root.querySelector('#ts-modal'),status=root.querySelector('#ts-status');root.querySelector('#ts-connect-btn').onclick=()=>{modal.style.display='flex';root.querySelector('#ts-code').focus()};root.querySelector('#ts-close').onclick=()=>modal.style.display='none';root.querySelector('#ts-test').onclick=async()=>{const c=root.querySelector('#ts-code').value.trim().toUpperCase(),u=root.querySelector('#ts-url').value.trim();if(!c&&!u){status.textContent='❌ Office Code enter karein';return}localStorage.setItem(K.code,c);localStorage.setItem(K.url,u||'http://127.0.0.1:9101');localStorage.removeItem(K.company);status.textContent='⏳ Checking Tally...';try{const raw=await collection('Connection Test','Company','Name',false);if(/LINEERROR|<ERROR/i.test(raw))throw Error('Tally returned an error');status.textContent='✅ Tally connected. Loading companies...';const data=await loadCompanies();status.textContent='✅ Connected · '+(selected()?.Name||'');setTimeout(()=>modal.style.display='none',700)}catch(e){status.textContent='❌ '+e.message}};window.__tsPanel={loadCompanies,loadLiveData}}
function start(){brand();hideOnlyOldButton();panel();setInterval(hideOnlyOldButton,1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
